// Exe 1: What output is generated by this program
// Enter hex digits and a floating-point number
#include <iostream>
#include <iomanip>
using namespace std;

int main()
{
    // Hex to decimal
    int number = 0;

    cout << "\nEnter a hexadecimal number followed by <return>: ";
    cin >> hex >> number;
    cout << "Your decimal input: " << number << endl;

    // If an invalid input occured:
    // Clears the buffer and reset error flags
    cin.sync();
    cin.clear();

    // Take two double as an input and do the opertion sum, multiplication
    // precision = 2, fixed, width = 10

    double x1 = 0.0, x2 = 0.0;
    cout << "\nNow enter two floating point values: " << endl;
    cout << "\n1. number: ";
    cin >> x1;
    cout << "\n2. number: ";
    cin >> x2;

    cout << fixed << setprecision(2)
         << "\nThe sum of both numbers: " << setw(10) << x1 + x2 << endl;
    cout << fixed << setprecision(2)
         << "\nThe product of both numbers: " << setw(10) << x1 * x2 << endl;
    return 0;
}